## more info on this configuration file: https://www.netlify.com/docs/netlify-toml-reference/

[build]
  command = "VITE_COMMIT_REF=$COMMIT_REF npm run build"
  publish = "dist"
  functions = "functions"

[[redirects]]
  from = "/ham2k-proxy/logbook.qrz.com/*"
  to = "https://logbook.qrz.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/country-files/bigcty/cty.csv"
  to = "https://www.country-files.com/bigcty/cty.csv"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  port = 4212 # Port that the dev server will be listening on
  targetPort = 4202 # Port where the undelying dev server will run on
  command = "npm start" # Command to start the undelying dev server
  publish = "public" # Folder with the static content for _redirect file


